# Generated by Django 5.1.6 on 2025-03-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NID_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
