# Generated by Django 5.1.7 on 2025-03-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0002_nid_db_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='nid_db',
            name='DoB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nid_db',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='nid_db',
            name='father_name',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='nid_db',
            name='mother_name',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='nid_db',
            name='name',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='nid_db',
            name='phone_number',
            field=models.CharField(default='0000000', max_length=15, unique=True),
        ),
    ]
